# Disabled rules
disabled_rules:
  - trailing_whitespace
  - todo
  - multiple_closures_with_trailing_closure # Common in SwiftUI views
  
# Enabled rules
opt_in_rules:
  - array_init
  - attributes
  - closure_spacing
  - collection_alignment
  - contains_over_filter_count
  - convenience_type
  - empty_collection_literal
  - empty_count
  - empty_string
  - explicit_init
  - fatal_error_message
  - first_where
  - force_unwrapping
  - implicitly_unwrapped_optional
  - legacy_random
  - literal_expression_end_indentation
  - multiline_parameters
  - operator_usage_whitespace
  - overridden_super_call
  - private_outlet
  - prohibited_super_call
  - redundant_nil_coalescing
  - redundant_type_annotation
  - strict_fileprivate
  - toggle_bool
  - unneeded_parentheses_in_closure_argument
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_closing_braces
  
# Customized rules
line_length:
  warning: 120
  error: 150
  
function_body_length:
  warning: 60
  error: 100
  
type_body_length:
  warning: 300
  error: 500
  
file_length:
  warning: 500
  error: 1000
  
cyclomatic_complexity:
  warning: 15
  error: 25
  
identifier_name:
  min_length: 2
  excluded:
    - id
    - x
    - y
    - z
    - dx
    - dy
    - dz
    
# Files/directories to ignore during linting
excluded:
  - .swiftlint.yml
  - .cursor
  - Documentation
  - **/PfizerOutdoCancer.xcodeproj
  - **/Packages
  - **/.git 

  - Pods
  - .build
  - DerivedData
  - fastlane
  - RealityKitContent # Exclude RealityKit content package if needed
  
# Only include swift files for linting (whitelisting source code)
included:
  - PfizerOutdoCancer/**/*.swift
  - PfizerOutdoCancerTests/**/*.swift 